opt_in_rules:
  - sorted_imports
  - file_header

disabled_rules:
  - force_try
  - switch_case_alignment

line_length: 150

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

file_header:
  severity: error


identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - all
    - url
    - tmp

reporter: "xcode"